2025-03-09 22:43:35,793 INFO    Thread-21 (_run_job):10252 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_224335-7z2g3shv\logs\debug.log
2025-03-09 22:43:35,793 INFO    Thread-21 (_run_job):10252 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_224335-7z2g3shv\logs\debug-internal.log
2025-03-09 22:43:35,793 INFO    Thread-21 (_run_job):10252 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:43:35,793 INFO    Thread-21 (_run_job):10252 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'relu', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 3, 'optimizer': 'rmsprop', 'weightDecay': 0.0005, 'weightInit': 'random'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:43:35,793 INFO    Thread-21 (_run_job):10252 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:43:35,956 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/7z2g3shv
2025-03-09 22:43:35,972 ERROR   Thread-21 (_run_job):10252 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:43:35,972 INFO    Thread-21 (_run_job):10252 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:43:35,972 INFO    Thread-21 (_run_job):10252 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:43:35,972 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:43:35,972 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_restore():2322] restore
2025-03-09 22:43:35,972 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:43:38,061 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:43:38,061 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:43:38,061 INFO    Thread-21 (_run_job):10252 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:43:38,066 ERROR   MainThread:10252 [pyagent.py:_run_jobs_from_queue():234] Run 7z2g3shv errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_10252\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_10252\1422709722.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_10252\1422709722.py", line 163, in backpropagation
    self.biases[i] -= learning_rate * db / (np.sqrt(self.squared_b[i]) + epsilon)
ValueError: non-broadcastable output operand with shape (64,1) doesn't match the broadcast shape (64,164)

2025-03-09 22:43:38,066 ERROR   MainThread:10252 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
