2025-03-17 14:52:18,157 INFO    Thread-19 (_run_job):20972 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250317_145218-8cxpg4wv\logs\debug.log
2025-03-17 14:52:18,157 INFO    Thread-19 (_run_job):20972 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250317_145218-8cxpg4wv\logs\debug-internal.log
2025-03-17 14:52:18,157 INFO    Thread-19 (_run_job):20972 [wandb_init.py:init():761] calling init triggers
2025-03-17 14:52:18,157 INFO    Thread-19 (_run_job):20972 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunction': 'relu', 'batchSize': 16, 'epochs': 5, 'hiddenLayerSize': 32, 'hiddenLayers': 4, 'learningRate': 0.001, 'optimizer': 'nadam', 'weightDecay': 0.5, 'weightInitialisation': 'random'}
config: {'epochs': 5, 'hiddenLayers': 3, 'hiddenLayerSize': 32, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'sgd', 'batchSize': 16, 'weightInitialisation': 'random', 'activationFunction': 'tanh', '_wandb': {}}
2025-03-17 14:52:18,157 INFO    Thread-19 (_run_job):20972 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-17 14:52:18,282 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/8cxpg4wv
2025-03-17 14:52:18,283 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-17 14:52:18,283 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_restore():2322] restore
2025-03-17 14:52:18,283 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_restore():2328] restore done
2025-03-17 14:52:21,314 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-17 14:52:21,314 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-17 14:52:21,314 INFO    Thread-19 (_run_job):20972 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-17 14:52:21,317 ERROR   MainThread:20972 [pyagent.py:_run_jobs_from_queue():234] Run 8cxpg4wv errored:
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\456.py", line 103, in sweep_hyperparameters
    model.train(x_train, y_train, x_val, y_val, epochs, weightDecay, learningRate, optimizer, batchSize, weightInitialisation, activationFunction)
  File "c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\nn.py", line 39, in train
    self.forward(x_batch, activation_funtion)
  File "c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\nn.py", line 138, in forward
    x = f(np.dot(w, x) + b)
        ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\nn.py", line 155, in relu
    return max(x, 0)
           ^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

2025-03-17 14:52:21,320 ERROR   MainThread:20972 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
