2025-03-09 22:31:33,184 INFO    Thread-11 (_run_job):14716 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223133-xytw9jv5\logs\debug.log
2025-03-09 22:31:33,184 INFO    Thread-11 (_run_job):14716 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223133-xytw9jv5\logs\debug-internal.log
2025-03-09 22:31:33,185 INFO    Thread-11 (_run_job):14716 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:31:33,186 INFO    Thread-11 (_run_job):14716 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'relu', 'batchSize': 164, 'hiddenLayer_Size': 32, 'learningRate': 0.001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'adam', 'weightDecay': 0.5, 'weightInit': 'random'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:31:33,188 INFO    Thread-11 (_run_job):14716 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:31:33,710 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/xytw9jv5
2025-03-09 22:31:33,712 ERROR   Thread-11 (_run_job):14716 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:31:33,712 INFO    Thread-11 (_run_job):14716 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:31:33,712 INFO    Thread-11 (_run_job):14716 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:31:33,712 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:31:33,712 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_restore():2322] restore
2025-03-09 22:31:33,712 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:31:35,367 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:31:35,367 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:31:35,367 INFO    Thread-11 (_run_job):14716 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:31:35,381 ERROR   MainThread:14716 [pyagent.py:_run_jobs_from_queue():234] Run xytw9jv5 errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\3018271561.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\3018271561.py", line 108, in forward
    x = self.sigmoid(np.dot(w,x) + b)
                     ^^^^^^^^^^^
ValueError: shapes (784,32) and (784,164) not aligned: 32 (dim 1) != 784 (dim 0)

2025-03-09 22:31:40,412 INFO    MsgRouterThr:14716 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:31:41,433 INFO    Thread-16 (_run_job):14716 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:31:41,435 INFO    Thread-16 (_run_job):14716 [wandb_setup.py:_flush():67] Configure stats pid to 14716
2025-03-09 22:31:41,435 INFO    Thread-16 (_run_job):14716 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:31:41,435 INFO    Thread-16 (_run_job):14716 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223141-gm8idqbp\logs\debug.log
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223141-gm8idqbp\logs\debug-internal.log
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000018C1FB2B020>
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 132, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0, 'weightInit': 'random'}
config: {'_wandb': {}}
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():784] starting backend
2025-03-09 22:31:41,436 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:31:41,443 INFO    Thread-16 (_run_job):14716 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:31:41,444 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:31:41,447 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'sigmoid', 'batchSize': 132, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0, 'weightInit': 'random'}
2025-03-09 22:31:41,459 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:31:41,478 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:31:41,541 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:31:43,247 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:31:43,541 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:31:43,541 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:31:43,541 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:31:43,542 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:31:43,544 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:31:43,545 INFO    Thread-16 (_run_job):14716 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223143-gm8idqbp\logs\debug.log
2025-03-09 22:31:43,545 INFO    Thread-16 (_run_job):14716 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223143-gm8idqbp\logs\debug-internal.log
2025-03-09 22:31:43,545 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:31:43,545 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 132, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0, 'weightInit': 'random'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:31:43,545 INFO    Thread-16 (_run_job):14716 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:31:44,066 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/gm8idqbp
2025-03-09 22:31:44,067 ERROR   Thread-16 (_run_job):14716 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:31:44,067 INFO    Thread-16 (_run_job):14716 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:31:44,067 INFO    Thread-16 (_run_job):14716 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:31:44,067 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:31:44,067 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_restore():2322] restore
2025-03-09 22:31:44,069 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:31:46,131 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:31:46,131 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:31:46,131 INFO    Thread-16 (_run_job):14716 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:31:46,144 ERROR   MainThread:14716 [pyagent.py:_run_jobs_from_queue():234] Run gm8idqbp errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\3018271561.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\3018271561.py", line 108, in forward
    x = self.sigmoid(np.dot(w,x) + b)
                     ^^^^^^^^^^^
ValueError: shapes (784,64) and (784,132) not aligned: 64 (dim 1) != 784 (dim 0)

2025-03-09 22:31:51,159 INFO    MsgRouterThr:14716 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_setup.py:_flush():67] Configure stats pid to 14716
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223152-ei4zv2xn\logs\debug.log
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223152-ei4zv2xn\logs\debug-internal.log
2025-03-09 22:31:52,159 INFO    Thread-21 (_run_job):14716 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000018C1FB286B0>
2025-03-09 22:31:52,167 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:31:52,167 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'adam', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'_wandb': {}}
2025-03-09 22:31:52,167 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():784] starting backend
2025-03-09 22:31:52,167 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:31:52,167 INFO    Thread-21 (_run_job):14716 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:31:52,170 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:31:52,172 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'adam', 'weightDecay': 0.5, 'weightInit': 'xavier'}
2025-03-09 22:31:52,174 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:31:52,196 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:31:52,259 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:31:53,963 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:31:54,224 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:31:54,225 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:31:54,226 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:31:54,226 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:31:54,227 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:31:54,235 INFO    Thread-21 (_run_job):14716 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223154-ei4zv2xn\logs\debug.log
2025-03-09 22:31:54,235 INFO    Thread-21 (_run_job):14716 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223154-ei4zv2xn\logs\debug-internal.log
2025-03-09 22:31:54,235 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:31:54,235 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 5, 'optimizer': 'adam', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:31:54,235 INFO    Thread-21 (_run_job):14716 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:31:54,375 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/ei4zv2xn
2025-03-09 22:31:54,377 ERROR   Thread-21 (_run_job):14716 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:31:54,378 INFO    Thread-21 (_run_job):14716 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:31:54,378 INFO    Thread-21 (_run_job):14716 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:31:54,378 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:31:54,378 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_restore():2322] restore
2025-03-09 22:31:54,378 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:31:56,466 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:31:56,466 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:31:56,466 INFO    Thread-21 (_run_job):14716 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:31:56,472 ERROR   MainThread:14716 [pyagent.py:_run_jobs_from_queue():234] Run ei4zv2xn errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\3018271561.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_14716\3018271561.py", line 108, in forward
    x = self.sigmoid(np.dot(w,x) + b)
                     ^^^^^^^^^^^
ValueError: shapes (784,64) and (784,164) not aligned: 64 (dim 1) != 784 (dim 0)

2025-03-09 22:31:56,474 ERROR   MainThread:14716 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
