2025-03-09 22:08:34,131 INFO    Thread-16 (_run_job):12776 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_220834-gvzdw2u4\logs\debug.log
2025-03-09 22:08:34,131 INFO    Thread-16 (_run_job):12776 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_220834-gvzdw2u4\logs\debug-internal.log
2025-03-09 22:08:34,131 INFO    Thread-16 (_run_job):12776 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:08:34,131 INFO    Thread-16 (_run_job):12776 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'relu', 'batchSize': 164, 'hiddenLayer_Size': 128, 'learningRate': 0.001, 'num_epochs': 20, 'num_hiddenLayers': 5, 'optimizer': 'rmsprop', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:08:34,131 INFO    Thread-16 (_run_job):12776 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:08:34,232 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/gvzdw2u4
2025-03-09 22:08:34,241 ERROR   Thread-16 (_run_job):12776 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:08:34,241 INFO    Thread-16 (_run_job):12776 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:08:34,241 INFO    Thread-16 (_run_job):12776 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:08:34,241 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:08:34,241 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_restore():2322] restore
2025-03-09 22:08:34,241 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:08:36,360 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:08:36,360 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:08:36,360 INFO    Thread-16 (_run_job):12776 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:08:36,371 ERROR   MainThread:12776 [pyagent.py:_run_jobs_from_queue():234] Run gvzdw2u4 errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_12776\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_12776\2685923661.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_12776\2685923661.py", line 107, in forward
    x = self.sigmoid(np.dot(x, w) + b)
                     ^^^^^^^^^^^^
ValueError: shapes (784,164) and (784,128) not aligned: 164 (dim 1) != 784 (dim 0)

2025-03-09 22:08:37,381 INFO    MsgRouterThr:12776 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_setup.py:_flush():67] Configure stats pid to 12776
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_220838-0pfbag62\logs\debug.log
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_220838-0pfbag62\logs\debug-internal.log
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002895378DC70>
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 132, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 10, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0.5, 'weightInit': 'random'}
config: {'_wandb': {}}
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():784] starting backend
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:08:38,393 INFO    Thread-21 (_run_job):12776 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:08:38,398 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:08:38,398 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'tanh', 'batchSize': 132, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 10, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0.5, 'weightInit': 'random'}
2025-03-09 22:08:38,400 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:08:38,417 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:08:38,467 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:08:39,834 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:08:40,074 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:08:40,075 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:08:40,075 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:08:40,075 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:08:40,076 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:08:40,078 INFO    Thread-21 (_run_job):12776 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_220840-0pfbag62\logs\debug.log
2025-03-09 22:08:40,078 INFO    Thread-21 (_run_job):12776 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_220840-0pfbag62\logs\debug-internal.log
2025-03-09 22:08:40,078 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:08:40,078 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 132, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 10, 'num_hiddenLayers': 4, 'optimizer': 'momentum', 'weightDecay': 0.5, 'weightInit': 'random'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:08:40,078 INFO    Thread-21 (_run_job):12776 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:08:40,193 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/0pfbag62
2025-03-09 22:08:40,196 ERROR   Thread-21 (_run_job):12776 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:08:40,196 INFO    Thread-21 (_run_job):12776 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:08:40,196 INFO    Thread-21 (_run_job):12776 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:08:40,196 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:08:40,196 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_restore():2322] restore
2025-03-09 22:08:40,196 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:08:42,343 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:08:42,343 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:08:42,343 INFO    Thread-21 (_run_job):12776 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:08:42,356 ERROR   MainThread:12776 [pyagent.py:_run_jobs_from_queue():234] Run 0pfbag62 errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_12776\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_12776\2685923661.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_12776\2685923661.py", line 107, in forward
    x = self.sigmoid(np.dot(x, w) + b)
                     ^^^^^^^^^^^^
ValueError: shapes (784,132) and (784,128) not aligned: 132 (dim 1) != 784 (dim 0)

2025-03-09 22:08:42,358 ERROR   MainThread:12776 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
