2025-03-09 22:34:56,849 INFO    Thread-16 (_run_job):4152 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223456-1rktfopr\logs\debug.log
2025-03-09 22:34:56,849 INFO    Thread-16 (_run_job):4152 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223456-1rktfopr\logs\debug-internal.log
2025-03-09 22:34:56,851 INFO    Thread-16 (_run_job):4152 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:34:56,851 INFO    Thread-16 (_run_job):4152 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'relu', 'batchSize': 132, 'hiddenLayer_Size': 64, 'learningRate': 0.001, 'num_epochs': 10, 'num_hiddenLayers': 3, 'optimizer': 'nadam', 'weightDecay': 0.0005, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:34:56,852 INFO    Thread-16 (_run_job):4152 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:34:56,984 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/1rktfopr
2025-03-09 22:34:56,986 ERROR   Thread-16 (_run_job):4152 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:34:56,986 INFO    Thread-16 (_run_job):4152 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:34:56,986 INFO    Thread-16 (_run_job):4152 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:34:56,986 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:34:56,986 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_restore():2322] restore
2025-03-09 22:34:56,986 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:34:59,047 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:34:59,047 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:34:59,047 INFO    Thread-16 (_run_job):4152 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:34:59,061 ERROR   MainThread:4152 [pyagent.py:_run_jobs_from_queue():234] Run 1rktfopr errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_4152\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_4152\3068522397.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_4152\3068522397.py", line 138, in backpropagation
    dw = self.layers[i].T.dot(deltas[i]) / m
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (132,784) and (64,132) not aligned: 784 (dim 1) != 64 (dim 0)

2025-03-09 22:35:05,059 INFO    MsgRouterThr:4152 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:35:06,108 INFO    Thread-21 (_run_job):4152 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_setup.py:_flush():67] Configure stats pid to 4152
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223506-8pgp82jy\logs\debug.log
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223506-8pgp82jy\logs\debug-internal.log
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002BC959E9250>
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 116, 'hiddenLayer_Size': 32, 'learningRate': 0.001, 'num_epochs': 10, 'num_hiddenLayers': 4, 'optimizer': 'sgd', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'_wandb': {}}
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():784] starting backend
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:35:06,109 INFO    Thread-21 (_run_job):4152 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:35:06,114 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:35:06,114 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'tanh', 'batchSize': 116, 'hiddenLayer_Size': 32, 'learningRate': 0.001, 'num_epochs': 10, 'num_hiddenLayers': 4, 'optimizer': 'sgd', 'weightDecay': 0.5, 'weightInit': 'xavier'}
2025-03-09 22:35:06,116 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:35:06,134 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:35:06,192 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:35:07,840 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:35:08,118 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:35:08,119 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:35:08,119 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:35:08,119 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:35:08,120 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:35:08,125 INFO    Thread-21 (_run_job):4152 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223508-8pgp82jy\logs\debug.log
2025-03-09 22:35:08,125 INFO    Thread-21 (_run_job):4152 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_223508-8pgp82jy\logs\debug-internal.log
2025-03-09 22:35:08,125 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:35:08,125 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 116, 'hiddenLayer_Size': 32, 'learningRate': 0.001, 'num_epochs': 10, 'num_hiddenLayers': 4, 'optimizer': 'sgd', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:35:08,125 INFO    Thread-21 (_run_job):4152 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:35:08,731 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/8pgp82jy
2025-03-09 22:35:08,732 ERROR   Thread-21 (_run_job):4152 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:35:08,732 INFO    Thread-21 (_run_job):4152 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:35:08,732 INFO    Thread-21 (_run_job):4152 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:35:08,732 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:35:08,732 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_restore():2322] restore
2025-03-09 22:35:08,732 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:35:10,205 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:35:10,205 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:35:10,206 INFO    Thread-21 (_run_job):4152 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:35:10,215 ERROR   MainThread:4152 [pyagent.py:_run_jobs_from_queue():234] Run 8pgp82jy errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_4152\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_4152\3068522397.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_4152\3068522397.py", line 138, in backpropagation
    dw = self.layers[i].T.dot(deltas[i]) / m
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (116,784) and (32,116) not aligned: 784 (dim 1) != 32 (dim 0)

2025-03-09 22:35:10,216 ERROR   MainThread:4152 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
