2025-03-09 22:41:29,792 INFO    Thread-21 (_run_job):3992 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_224129-v7t2hujs\logs\debug.log
2025-03-09 22:41:29,792 INFO    Thread-21 (_run_job):3992 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_224129-v7t2hujs\logs\debug-internal.log
2025-03-09 22:41:29,792 INFO    Thread-21 (_run_job):3992 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:41:29,801 INFO    Thread-21 (_run_job):3992 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 164, 'hiddenLayer_Size': 64, 'learningRate': 0.001, 'num_epochs': 20, 'num_hiddenLayers': 4, 'optimizer': 'adam', 'weightDecay': 0.5, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:41:29,801 INFO    Thread-21 (_run_job):3992 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:41:29,947 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/v7t2hujs
2025-03-09 22:41:29,951 ERROR   Thread-21 (_run_job):3992 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:41:29,951 INFO    Thread-21 (_run_job):3992 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:41:29,952 INFO    Thread-21 (_run_job):3992 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:41:29,952 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:41:29,952 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_restore():2322] restore
2025-03-09 22:41:29,952 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:41:31,954 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:41:31,954 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:41:31,956 INFO    Thread-21 (_run_job):3992 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:41:31,971 ERROR   MainThread:3992 [pyagent.py:_run_jobs_from_queue():234] Run v7t2hujs errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_3992\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_3992\2451862988.py", line 61, in train
    self.backpropagation(x_batch, y_batch, learning_rate, optimizer)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_3992\2451862988.py", line 167, in backpropagation
    self.velocities_w[i] = beta1 * self.velocities_w[i] + (1 - beta1) * dw
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (64,784) (784,64) 

2025-03-09 22:41:31,976 ERROR   MainThread:3992 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
