2025-03-09 22:12:39,755 INFO    Thread-11 (_run_job):19348 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221239-9lugk1ue\logs\debug.log
2025-03-09 22:12:39,757 INFO    Thread-11 (_run_job):19348 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221239-9lugk1ue\logs\debug-internal.log
2025-03-09 22:12:39,757 INFO    Thread-11 (_run_job):19348 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:12:39,757 INFO    Thread-11 (_run_job):19348 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 132, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 3, 'optimizer': 'nesterov', 'weightDecay': 0.5, 'weightInit': 'random'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:12:39,757 INFO    Thread-11 (_run_job):19348 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:12:39,967 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/9lugk1ue
2025-03-09 22:12:39,970 ERROR   Thread-11 (_run_job):19348 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:12:39,971 INFO    Thread-11 (_run_job):19348 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:12:39,971 INFO    Thread-11 (_run_job):19348 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:12:39,971 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:12:39,971 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_restore():2322] restore
2025-03-09 22:12:39,971 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:12:41,912 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:12:41,912 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:12:41,912 INFO    Thread-11 (_run_job):19348 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:12:41,917 ERROR   MainThread:19348 [pyagent.py:_run_jobs_from_queue():234] Run 9lugk1ue errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\4057043383.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\4057043383.py", line 113, in forward
    output = self.softmax(np.dot(x, self.weights[-1]) + self.biases[-1])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (128,132) and (128,10) not aligned: 132 (dim 1) != 128 (dim 0)

2025-03-09 22:12:46,936 INFO    MsgRouterThr:19348 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:12:47,943 INFO    Thread-16 (_run_job):19348 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:12:47,943 INFO    Thread-16 (_run_job):19348 [wandb_setup.py:_flush():67] Configure stats pid to 19348
2025-03-09 22:12:47,943 INFO    Thread-16 (_run_job):19348 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:12:47,954 INFO    Thread-16 (_run_job):19348 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221247-ayqinsfy\logs\debug.log
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221247-ayqinsfy\logs\debug-internal.log
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002176D129AF0>
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 3, 'optimizer': 'sgd', 'weightDecay': 0, 'weightInit': 'xavier'}
config: {'_wandb': {}}
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():784] starting backend
2025-03-09 22:12:47,955 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:12:47,959 INFO    Thread-16 (_run_job):19348 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:12:47,959 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:12:47,961 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 3, 'optimizer': 'sgd', 'weightDecay': 0, 'weightInit': 'xavier'}
2025-03-09 22:12:47,963 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:12:47,982 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:12:48,041 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:12:49,792 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:12:50,072 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:12:50,072 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:12:50,072 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:12:50,072 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:12:50,073 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:12:50,076 INFO    Thread-16 (_run_job):19348 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221250-ayqinsfy\logs\debug.log
2025-03-09 22:12:50,076 INFO    Thread-16 (_run_job):19348 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221250-ayqinsfy\logs\debug-internal.log
2025-03-09 22:12:50,076 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:12:50,076 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'tanh', 'batchSize': 164, 'hiddenLayer_Size': 128, 'learningRate': 0.0001, 'num_epochs': 20, 'num_hiddenLayers': 3, 'optimizer': 'sgd', 'weightDecay': 0, 'weightInit': 'xavier'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:12:50,076 INFO    Thread-16 (_run_job):19348 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:12:50,212 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/ayqinsfy
2025-03-09 22:12:50,213 ERROR   Thread-16 (_run_job):19348 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:12:50,213 INFO    Thread-16 (_run_job):19348 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:12:50,213 INFO    Thread-16 (_run_job):19348 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:12:50,213 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:12:50,213 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_restore():2322] restore
2025-03-09 22:12:50,213 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:12:52,467 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:12:52,467 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:12:52,467 INFO    Thread-16 (_run_job):19348 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:12:52,481 ERROR   MainThread:19348 [pyagent.py:_run_jobs_from_queue():234] Run ayqinsfy errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\4057043383.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\4057043383.py", line 113, in forward
    output = self.softmax(np.dot(x, self.weights[-1]) + self.biases[-1])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (128,164) and (128,10) not aligned: 164 (dim 1) != 128 (dim 0)

2025-03-09 22:12:57,499 INFO    MsgRouterThr:19348 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-03-09 22:12:58,508 INFO    Thread-21 (_run_job):19348 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-09 22:12:58,508 INFO    Thread-21 (_run_job):19348 [wandb_setup.py:_flush():67] Configure stats pid to 19348
2025-03-09 22:12:58,515 INFO    Thread-21 (_run_job):19348 [wandb_setup.py:_flush():67] Loading settings from C:\Users\prajv\.config\wandb\settings
2025-03-09 22:12:58,515 INFO    Thread-21 (_run_job):19348 [wandb_setup.py:_flush():67] Loading settings from c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\settings
2025-03-09 22:12:58,515 INFO    Thread-21 (_run_job):19348 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221258-8vvffu15\logs\debug.log
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221258-8vvffu15\logs\debug-internal.log
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000021769BC3EC0>
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 116, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 3, 'optimizer': 'adam', 'weightDecay': 0, 'weightInit': 'random'}
config: {'_wandb': {}}
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():784] starting backend
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():788] sending inform_init request
2025-03-09 22:12:58,516 INFO    Thread-21 (_run_job):19348 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-09 22:12:58,521 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():798] backend started and connected
2025-03-09 22:12:58,522 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_config_callback():1261] config_cb None None {'activationFunc': 'sigmoid', 'batchSize': 116, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 3, 'optimizer': 'adam', 'weightDecay': 0, 'weightInit': 'random'}
2025-03-09 22:12:58,524 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-09 22:12:58,549 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():891] updated telemetry
2025-03-09 22:12:58,619 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-09 22:13:00,543 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():990] starting run threads in backend
2025-03-09 22:13:00,818 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_console_start():2375] atexit reg
2025-03-09 22:13:00,819 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-09 22:13:00,820 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-09 22:13:00,820 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-09 22:13:00,821 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-09 22:13:00,821 INFO    Thread-21 (_run_job):19348 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221300-8vvffu15\logs\debug.log
2025-03-09 22:13:00,829 INFO    Thread-21 (_run_job):19348 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\prajv\Downloads\ass1\DA6401_ASSIGNMENT1\wandb\run-20250309_221300-8vvffu15\logs\debug-internal.log
2025-03-09 22:13:00,829 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():761] calling init triggers
2025-03-09 22:13:00,829 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activationFunc': 'sigmoid', 'batchSize': 116, 'hiddenLayer_Size': 64, 'learningRate': 0.0001, 'num_epochs': 5, 'num_hiddenLayers': 3, 'optimizer': 'adam', 'weightDecay': 0, 'weightInit': 'random'}
config: {'num_epochs': 10, 'num_hiddenLayers': 3, 'hiddenLayer_Size': 40, 'weightDecay': 0, 'learningRate': 0.001, 'optimizer': 'Nesterov_Accelerated_GD', 'batchSize': 32, 'weightInit': 'xavier', 'activationFunc': 'sigmoid', '_wandb': {}}
2025-03-09 22:13:00,829 INFO    Thread-21 (_run_job):19348 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 22:13:00,993 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_finish():2112] finishing run da6401-assignments/assignment1/8vvffu15
2025-03-09 22:13:00,996 ERROR   Thread-21 (_run_job):19348 [jupyter.py:save_history():450] Run pip install nbformat to save notebook history
2025-03-09 22:13:00,996 INFO    Thread-21 (_run_job):19348 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-09 22:13:00,996 INFO    Thread-21 (_run_job):19348 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-09 22:13:00,997 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-03-09 22:13:00,997 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_restore():2322] restore
2025-03-09 22:13:00,997 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_restore():2328] restore done
2025-03-09 22:13:03,627 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-09 22:13:03,627 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-09 22:13:03,627 INFO    Thread-21 (_run_job):19348 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-09 22:13:03,631 ERROR   MainThread:19348 [pyagent.py:_run_jobs_from_queue():234] Run 8vvffu15 errored:
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\wandb\agents\pyagent.py", line 306, in _run_job
    self._function()
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\1058529509.py", line 36, in sweep_hyperParameters
    model.train(x_train, y_train, x_val, y_val, num_epochs, learningRate, optimizer, batchSize)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\4057043383.py", line 60, in train
    self.forward(x_batch)
  File "C:\Users\prajv\AppData\Local\Temp\ipykernel_19348\4057043383.py", line 113, in forward
    output = self.softmax(np.dot(x, self.weights[-1]) + self.biases[-1])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (64,116) and (64,10) not aligned: 116 (dim 1) != 64 (dim 0)

2025-03-09 22:13:03,631 ERROR   MainThread:19348 [pyagent.py:_run_jobs_from_queue():245] Detected 3 failed runs in the first 60 seconds, killing sweep.
